;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                                                                                                                                                ;;
;;                                                                ** SPLIT PHP FRAMEWORK **                                                                       ;;
;; This file is part of *SPLIT PHP Framework*                                                                                                                     ;;
;;                                                                                                                                                                ;;
;; Why "SPLIT"? Firstly because the word "split" is a reference to micro-services and split systems architecture (of course you can make monoliths with it,       ;;
;; if that's your thing). Furthermore, it is an acronym for these 5 bound concepts which are the bases that this framework leans on, which are: "Simplicity",     ;;
;; "Purity", "Lightness", "Intuitiveness", "Target Minded"                                                                                                        ;;
;;                                                                                                                                                                ;;
;; See more info about it at: https://github.com/gabriel-guelfi/split-php                                                                                         ;;
;;                                                                                                                                                                ;;
;; MIT License                                                                                                                                                    ;;
;;                                                                                                                                                                ;;
;; Copyright (c) 2025 Lightertools Open Source Community                                                                                                               ;;
;;                                                                                                                                                                ;;
;; Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to          ;;
;; deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or         ;;
;; sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:                            ;;
;;                                                                                                                                                                ;;
;; The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.                                 ;;
;;                                                                                                                                                                ;;
;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,FITNESS     ;;
;; FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY           ;;
;; WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.     ;;
;;                                                                                                                                                                ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[DATABASE]
DB_CONNECT = "off"
DBNAME = "your_database_name"
DBHOST = "your_database_host"
DBPORT = 3306
DBUSER_MAIN = "your_database_user_writer" 
DBPASS_MAIN = "your_database_writer_password"
DBUSER_READONLY = "your_database_reader_user" ;This credentials are used to perform the read operations on the database for security reasons.
DBPASS_READONLY = "your_database_reader_password" ;This credentials are used to perform the read operations on the database for security reasons.
DB_CHARSET = "utf8"
DBTYPE = "mysql"
DB_TRANSACTIONAL = "on"
DB_WORK_AROUND_FACTOR = 5
CACHE_DB_METADATA = "on"

[SYSTEM]
APPLICATION_NAME = "Application Example"
DEFAULT_ROUTE = "/site/home"
DEFAULT_TIMEZONE=""
HANDLE_ERROR_TYPES = E_ALL & ~E_NOTICE & ~E_USER_NOTICE ;Do not change this unless you know exactly what you're doing.
APPLICATION_LOG = "on"
PRIVATE_KEY = "generate_a_hash_to_insert_here" ;used for encryption and security
PUBLIC_KEY = "generate_a_hash_to_insert_here" ;used for encryption and security
ALLOW_CORS="on"
MAX_LOG_ENTRIES = 5

[VENDORS]

;Use it to create your own settings. Every configuration added here will be available throughout the entire application as uppercase constants.
;ATTENTION: do not put sensible data on this custom configurations section, as it isn't protected by environment variables as the other sections are.
[CUSTOM]
